eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8763
spring:
  zipkin:
    enabled: true
    baseUrl: http://127.0.0.1:9411
  application:
    name: ngcloud-service
