eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 18888
spring:
  zipkin:
    enabled: true
    baseUrl: http://127.0.0.1:9411
  application:
    name: ngcloud-client
